auto: true

markdown: kramdown
#rdiscount

highlighter: 'rouge'
#'pygments'

#paginate: 8
permalink: /:title

name: “pkokp8's Blog”
title: pkokp8's blog
description: 多搬点砖
url: https://pkokp8.github.io/
feed: /atom.xml
author_info: <a href="https://pkokp8.github.io/">pkokp8</a>
